services:
  - type: web
    name: reia-scraper
    runtime: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium-browser && \
      npm install
    startCommand: node server.js
